# Generated by Django 4.2.8 on 2024-01-22 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_book_favorites_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
